### INICIO PROYECTO 

Adquisición de datos y unión de las diferentes fuentes.

In [1]:
import pandas as pd
import numpy as np
import os
# Ignoramos unos warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
print(os.getcwd())

c:\Users\aisat\Desktop\DSPT25_RA\3-DSPT2025-ML\Proyecto final\RA_proyecto_final_ML\1.notebooks

In [3]:
df = pd.read_csv ("quejas-clientes.csv", sep=",")
df.head()

,Unnamed: 0,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
0,0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119.0,2015-03-19,2015-03-19,"Premium Asset Services, LLC",In progress,Yes,NaN
1,1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479.0,2015-03-19,2015-03-19,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN
2,2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127.0,2015-03-19,2015-03-19,RBS Citizens,Closed with explanation,Yes,Yes
3,3,1291615,Credit card,NaN,Other,NaN,CA,92592.0,2015-03-19,2015-03-19,Navy FCU,In progress,Yes,NaN
4,4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068.0,2015-03-19,2015-03-19,Transworld Systems Inc.,In progress,Yes,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28156 entries, 0 to 28155
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            28156 non-null  int64
 1   Complaint ID          28156 non-null  int64
 2   Product               28156 non-null  object
 3   Sub-product           17582 non-null  object
 4   Issue                 28154 non-null  object
 5   Sub-issue             13211 non-null  object
 6   State                 27735 non-null  object
 7   ZIP code              27876 non-null  float64
 8   Date received         28156 non-null  object
 9   Date sent to company  28156 non-null  object
 10  Company               28156 non-null  object
 11  Company response      28156 non-null  object
 12  Timely response?      28156 non-null  object
 13  Consumer disputed?    6006 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 3.0+ MB

In [5]:
print(df.isnull().sum())

Unnamed: 0                  0
Complaint ID                0
Product                     0
Sub-product             10574
Issue                       2
Sub-issue               14945
State                     421
ZIP code                  280
Date received               0
Date sent to company        0
Company                     0
Company response            0
Timely response?            0
Consumer disputed?      22150
dtype: int64

In [6]:
del df["Unnamed: 0"]

In [7]:
df.head()

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119.0,2015-03-19,2015-03-19,"Premium Asset Services, LLC",In progress,Yes,NaN
1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479.0,2015-03-19,2015-03-19,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN
2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127.0,2015-03-19,2015-03-19,RBS Citizens,Closed with explanation,Yes,Yes
3,1291615,Credit card,NaN,Other,NaN,CA,92592.0,2015-03-19,2015-03-19,Navy FCU,In progress,Yes,NaN
4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068.0,2015-03-19,2015-03-19,Transworld Systems Inc.,In progress,Yes,NaN

### Analizamos las diferentes columnas/variables numéricas y categóricas.

#### Product

In [8]:
print (df['Product'].sort_values(ascending=True).unique())
print (len(df['Product'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Product'].value_counts(ascending=False))
print("-"*40)
print (df['Product'].value_counts(normalize=True, ascending=False)*100)

['Bank account or service' 'Consumer loan' 'Credit card'
 'Credit reporting' 'Debt collection' 'Money transfers' 'Mortgage'
 'Other financial service' 'Payday loan' 'Prepaid card' 'Student loan']
11
----------------------------------------
Product
Debt collection            7494
Mortgage                   6612
Credit reporting           5717
Credit card                2830
Bank account or service    2609
Consumer loan              1314
Student loan                785
Payday loan                 348
Money transfers             232
Prepaid card                175
Other financial service      40
Name: count, dtype: int64
----------------------------------------
Product
Debt collection            26.615997
Mortgage                   23.483449
Credit reporting           20.304731
Credit card                10.051144
Bank account or service     9.266231
Consumer loan               4.666856
Student loan                2.788038
Payday loan                 1.235971
Money transfers             0.823981
Prepaid card                0.621537
Other financial service     0.142066
Name: proportion, dtype: float64

#### Sub-product

In [9]:
print (df['Sub-product'].sort_values(ascending=True).unique())
print (len(df['Sub-product'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Sub-product'].value_counts(ascending=False))
print("-"*40)
print (df['Sub-product'].value_counts(normalize=True, ascending=False)*100)
df[df['Sub-product'].isna()]

['(CD) Certificate of deposit' 'Auto' 'Cashing a check without an account'
 'Check cashing' 'Checking account'
 'Conventional adjustable mortgage (ARM)' 'Conventional fixed mortgage'
 'Credit card' 'Credit repair' 'Debt settlement'
 'Domestic (US) money transfer' 'FHA mortgage' 'Federal student loan'
 'Foreign currency exchange' 'General purpose card'
 'Gift or merchant card' 'Government benefit payment card'
 'Home equity loan or line of credit' 'ID prepaid card' 'Installment loan'
 'International money transfer' 'Medical' 'Mobile wallet' 'Money order'
 'Mortgage' 'Non-federal student loan' 'Other (phone, health club, etc.)'
 'Other bank product/service' 'Other mortgage'
 'Other special purpose card' 'Pawn loan' 'Payday loan' 'Payroll card'
 'Personal line of credit' 'Refund anticipation check' 'Reverse mortgage'
 'Savings account' 'Title loan' "Traveler's/Cashier's checks"
 'VA mortgage' 'Vehicle lease' 'Vehicle loan' nan]
43
----------------------------------------
Sub-product
Conventional fixed mortgage               2446
Other (phone, health club, etc.)          2273
Other mortgage                            1954
Checking account                          1693
Credit card                               1447
Medical                                   1135
Non-federal student loan                   911
FHA mortgage                               853
Conventional adjustable mortgage (ARM)     800
Vehicle loan                               721
Other bank product/service                 629
Payday loan                                397
Installment loan                           386
Home equity loan or line of credit         329
VA mortgage                                180
Mortgage                                   169
Savings account                            166
Auto                                       164
International money transfer               131
Vehicle lease                              126
Federal student loan                       104
Domestic (US) money transfer               101
(CD) Certificate of deposit                 99
General purpose card                        77
Reverse mortgage                            50
Personal line of credit                     38
Gift or merchant card                       35
Title loan                                  34
Mobile wallet                               25
Cashing a check without an account          22
Government benefit payment card             22
Check cashing                               16
Pawn loan                                    9
ID prepaid card                              8
Credit repair                                6
Other special purpose card                   5
Debt settlement                              5
Money order                                  5
Refund anticipation check                    3
Payroll card                                 3
Foreign currency exchange                    3
Traveler's/Cashier's checks                  2
Name: count, dtype: int64
----------------------------------------
Sub-product
Conventional fixed mortgage               13.911955
Other (phone, health club, etc.)          12.927995
Other mortgage                            11.113639
Checking account                           9.629166
Credit card                                8.230008
Medical                                    6.455466
Non-federal student loan                   5.181436
FHA mortgage                               4.851553
Conventional adjustable mortgage (ARM)     4.550108
Vehicle loan                               4.100785
Other bank product/service                 3.577522
Payday loan                                2.257991
Installment loan                           2.195427
Home equity loan or line of credit         1.871232
VA mortgage                                1.023774
Mortgage                                   0.961210
Savings account                            0.944147
Auto                                       0.932772
International money transfer               0.745080
Vehicle lease                              0.716642
Federal student loan                       0.591514
Domestic (US) money transfer               0.574451
(CD) Certificate of deposit                0.563076
General purpose card                       0.437948
Reverse mortgage                           0.284382
Personal line of credit                    0.216130
Gift or merchant card                      0.199067
Title loan                                 0.193380
Mobile wallet                              0.142191
Cashing a check without an account         0.125128
Government benefit payment card            0.125128
Check cashing                              0.091002
Pawn loan                                  0.051189
ID prepaid card                            0.045501
Credit repair                              0.034126
Other special purpose card                 0.028438
Debt settlement                            0.028438
Money order                                0.028438
Refund anticipation check                  0.017063
Payroll card                               0.017063
Foreign currency exchange                  0.017063
Traveler's/Cashier's checks                0.011375
Name: proportion, dtype: float64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119.0,2015-03-19,2015-03-19,"Premium Asset Services, LLC",In progress,Yes,NaN
3,1291615,Credit card,NaN,Other,NaN,CA,92592.0,2015-03-19,2015-03-19,Navy FCU,In progress,Yes,NaN
13,1289273,Payday loan,NaN,Can't contact lender,NaN,TX,78205.0,2015-03-18,2015-03-18,ACE Cash Express Inc.,In progress,Yes,NaN
15,1290486,Debt collection,NaN,Disclosure verification of debt,Not given enough info to verify debt,AL,36756.0,2015-03-18,2015-03-19,"Expert Global Solutions, Inc.",In progress,Yes,NaN
22,1289844,Debt collection,NaN,Improper contact or sharing of info,Contacted me after I asked not to,IL,60411.0,2015-03-18,2015-03-18,"Municipal Collections Services, Inc.",Closed with explanation,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28146,1178169,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,WA,98908.0,2015-01-01,2015-01-07,Experian,Closed with explanation,Yes,NaN
28149,1178177,Credit reporting,NaN,Improper use of my credit report,Report improperly shared by CRC,MI,48622.0,2015-01-01,2015-01-07,Experian,Closed with explanation,Yes,No
28150,1178179,Credit card,NaN,Late fee,NaN,AR,72160.0,2015-01-01,2015-01-02,U.S. Bancorp,Closed with monetary relief,Yes,No
28151,1178184,Debt collection,NaN,Cont'd attempts collect debt not owed,Debt is not mine,TX,75201.0,2015-01-01,2015-01-02,"Enhanced Recovery Company, LLC",Closed with non-monetary relief,Yes,No
28154,1178181,Payday loan,NaN,Can't stop charges to bank account,NaN,CA,92509.0,2015-01-01,2015-01-07,Moneytree Inc,Closed with explanation,Yes,NaN

#### Issue

In [10]:
print (df['Issue'].sort_values(ascending=True).unique())
print (len(df['Issue'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Issue'].value_counts(ascending=False))
print("-"*40)
print (df['Issue'].value_counts(normalize=True, ascending=False)*100)
df[df['Issue'].isna()]

['APR or interest rate' 'Account opening, closing, or management'
 'Account terms and changes' 'Adding money' 'Advertising and marketing'
 'Advertising, marketing or disclosures' 'Application processing delay'
 'Application, originator, mortgage broker'
 'Applied for loan/did not receive money' 'Arbitration' 'Balance transfer'
 'Balance transfer fee' 'Bankruptcy' 'Billing disputes'
 'Billing statement' "Can't contact lender" "Can't repay my loan"
 "Can't stop charges to bank account" 'Cash advance' 'Cash advance fee'
 'Charged bank acct wrong day or amt'
 "Charged fees or interest I didn't expect" 'Closing/Cancelling account'
 'Communication tactics' "Cont'd attempts collect debt not owed"
 'Convenience checks' 'Credit card protection / Debt protection'
 'Credit decision / Underwriting' 'Credit determination'
 'Credit line increase/decrease'
 'Credit monitoring or identity protection'
 "Credit reporting company's investigation"
 'Customer service / Customer relations'
 'Customer service/Customer relations'
 'Dealing with my lender or servicer' 'Delinquent account'
 'Deposits and withdrawals' 'Disclosure verification of debt'
 'Disclosures' 'Excessive fees' 'False statements or representation'
 'Fees' 'Forbearance / Workout plans' 'Fraud or scam' 'Getting a loan'
 'Identity theft / Fraud / Embezzlement'
 'Improper contact or sharing of info' 'Improper use of my credit report'
 'Incorrect exchange rate' 'Incorrect information on credit report'
 'Incorrect/missing disclosures or info' 'Late fee'
 'Lender damaged or destroyed vehicle'
 'Lender repossessed or sold the vehicle'
 'Loan modification,collection,foreclosure'
 'Loan servicing, payments, escrow account' 'Lost or stolen check'
 'Lost or stolen money order' 'Making/receiving payments, sending money'
 'Managing the line of credit' 'Managing the loan or lease'
 'Managing, opening, or closing account'
 'Money was not available when promised' 'Other' 'Other fee'
 'Other service issues' 'Other transaction issues'
 'Overdraft, savings or rewards features' 'Overlimit fee'
 'Payment to acct not credited' 'Payoff process' 'Privacy'
 'Problems caused by my funds being low'
 'Problems when you are unable to pay'
 "Received a loan I didn't apply for" 'Rewards' 'Sale of account'
 'Settlement process and costs' 'Shopping for a line of credit'
 'Shopping for a loan or lease' 'Taking out the loan or lease'
 'Taking/threatening an illegal action' 'Transaction issue'
 'Unable to get credit report/credit score'
 'Unauthorized transactions/trans. issues' 'Unexpected/Other fees'
 'Unsolicited issuance of credit card' 'Using a debit or ATM card'
 'Wrong amount charged or received' nan]

90
----------------------------------------
Issue
Incorrect information on credit report      4170
Cont'd attempts collect debt not owed       3351
Loan modification,collection,foreclosure    3049
Loan servicing, payments, escrow account    2627
Disclosure verification of debt             1300
                                            ...
Lost or stolen check                           2
Advertising, marketing or disclosures          2
Lender damaged or destroyed vehicle            2
Overdraft, savings or rewards features         1
Excessive fees                                 1
Name: count, Length: 89, dtype: int64
----------------------------------------
Issue
Incorrect information on credit report      14.811394
Cont'd attempts collect debt not owed       11.902394
Loan modification,collection,foreclosure    10.829722
Loan servicing, payments, escrow account     9.330823
Disclosure verification of debt              4.617461
                                              ...
Lost or stolen check                         0.007104
Advertising, marketing or disclosures        0.007104
Lender damaged or destroyed vehicle          0.007104
Overdraft, savings or rewards features       0.003552
Excessive fees                               0.003552
Name: proportion, Length: 89, dtype: float64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
11730,1235087,Bank account or service,Other bank product/service,NaN,NaN,FL,33428.0,2015-02-09,2015-02-10,Wells Fargo,Closed with explanation,Yes,NaN
13198,1226302,Bank account or service,Checking account,NaN,NaN,FL,33487.0,2015-02-05,2015-02-05,JPMorgan Chase,Closed with monetary relief,Yes,NaN

#### Sub-issue

In [11]:
print (df['Sub-issue'].sort_values(ascending=True).unique())
print (len(df['Sub-issue'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Sub-issue'].value_counts(ascending=False))
print("-"*40)
print (df['Sub-issue'].value_counts(normalize=True, ascending=False)*100)
df[df['Sub-issue'].isna()]

['Account status' 'Account terms' 'Account terms and changes'
 'Attempted to collect wrong amount' 'Attempted to/Collected exempt funds'
 'Billing dispute' 'Called after sent written cease of comm'
 'Called outside of 8am-9pm' 'Contacted employer after asked not to'
 'Contacted me after I asked not to' 'Contacted me instead of my attorney'
 'Debt is not mine' 'Debt resulted from identity theft'
 'Debt was discharged in bankruptcy' 'Debt was paid'
 'Frequent or repeated calls' 'Impersonated an attorney or official'
 'Inadequate help over the phone' 'Indicated committed crime not paying'
 "Indicated shouldn't respond to lawsuit" 'Information is not mine'
 'Investigation took too long' 'No notice of investigation status/result'
 'Not disclosed as an attempt to collect'
 'Not given enough info to verify debt' 'Personal information'
 'Problem cancelling or closing account'
 'Problem getting my free annual report'
 'Problem getting report or credit score' 'Problem with fraud alerts'
 'Problem with statement of dispute' 'Public record'
 'Received marketing offer after opted out'
 'Receiving unwanted marketing/advertising'
 'Reinserted previously deleted info' 'Report improperly shared by CRC'
 'Report shared with employer w/o consent'
 'Right to dispute notice not received'
 'Seized/Attempted to seize property'
 'Sued w/o proper notification of suit'
 "Sued where didn't live/sign for debt"
 'Talked to a third party about my debt'
 'Threatened arrest/jail if do not pay'
 'Threatened to sue on too old debt' 'Threatened to take legal action'
 'Used obscene/profane/abusive language' nan]
47
----------------------------------------
Sub-issue
Debt is not mine                            2125
Account status                              1604
Information is not mine                     1307
Debt was paid                                890
Not given enough info to verify debt         815
Frequent or repeated calls                   754
Account terms                                484
Attempted to collect wrong amount            482
Right to dispute notice not received         387
Problem getting my free annual report        386
Public record                                356
Talked to a third party about my debt        289
Personal information                         258
Threatened to take legal action              246
Problem with statement of dispute            243
No notice of investigation status/result     241
Debt resulted from identity theft            205
Problem getting report or credit score       198
Report improperly shared by CRC              162
Reinserted previously deleted info           161
Contacted employer after asked not to        149
Debt was discharged in bankruptcy            131
Threatened to sue on too old debt            128
Used obscene/profane/abusive language        111
Threatened arrest/jail if do not pay         109
Contacted me after I asked not to            109
Called after sent written cease of comm      100
Not disclosed as an attempt to collect        98
Investigation took too long                   86
Inadequate help over the phone                68
Impersonated an attorney or official          63
Indicated committed crime not paying          63
Problem with fraud alerts                     58
Sued w/o proper notification of suit          56
Seized/Attempted to seize property            55
Attempted to/Collected exempt funds           44
Called outside of 8am-9pm                     40
Billing dispute                               36
Account terms and changes                     24
Sued where didn't live/sign for debt          21
Problem cancelling or closing account         21
Indicated shouldn't respond to lawsuit        16
Receiving unwanted marketing/advertising      11
Report shared with employer w/o consent        9
Contacted me instead of my attorney            8
Received marketing offer after opted out       4
Name: count, dtype: int64
----------------------------------------
Sub-issue
Debt is not mine                            16.085081
Account status                              12.141397
Information is not mine                      9.893271
Debt was paid                                6.736810
Not given enough info to verify debt         6.169102
Frequent or repeated calls                   5.707365
Account terms                                3.663614
Attempted to collect wrong amount            3.648475
Right to dispute notice not received         2.929377
Problem getting my free annual report        2.921808
Public record                                2.694724
Talked to a third party about my debt        2.187571
Personal information                         1.952918
Threatened to take legal action              1.862085
Problem with statement of dispute            1.839376
No notice of investigation status/result     1.824237
Debt resulted from identity theft            1.551737
Problem getting report or credit score       1.498751
Report improperly shared by CRC              1.226251
Reinserted previously deleted info           1.218681
Contacted employer after asked not to        1.127848
Debt was discharged in bankruptcy            0.991598
Threatened to sue on too old debt            0.968890
Used obscene/profane/abusive language        0.840209
Threatened arrest/jail if do not pay         0.825070
Contacted me after I asked not to            0.825070
Called after sent written cease of comm      0.756945
Not disclosed as an attempt to collect       0.741806
Investigation took too long                  0.650973
Inadequate help over the phone               0.514723
Impersonated an attorney or official         0.476875
Indicated committed crime not paying         0.476875
Problem with fraud alerts                    0.439028
Sued w/o proper notification of suit         0.423889
Seized/Attempted to seize property           0.416320
Attempted to/Collected exempt funds          0.333056
Called outside of 8am-9pm                    0.302778
Billing dispute                              0.272500
Account terms and changes                    0.181667
Sued where didn't live/sign for debt         0.158958
Problem cancelling or closing account        0.158958
Indicated shouldn't respond to lawsuit       0.121111
Receiving unwanted marketing/advertising     0.083264
Report shared with employer w/o consent      0.068125
Contacted me instead of my attorney          0.060556
Received marketing offer after opted out     0.030278
Name: proportion, dtype: float64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127.0,2015-03-19,2015-03-19,RBS Citizens,Closed with explanation,Yes,Yes
3,1291615,Credit card,NaN,Other,NaN,CA,92592.0,2015-03-19,2015-03-19,Navy FCU,In progress,Yes,NaN
6,1288848,Consumer loan,Installment loan,Managing the loan or lease,NaN,OH,44241.0,2015-03-18,2015-03-18,"CashCall, Inc.",Closed with explanation,Yes,Yes
11,1288903,Bank account or service,Other bank product/service,Deposits and withdrawals,NaN,RI,2893.0,2015-03-18,2015-03-18,Santander Bank US,In progress,Yes,NaN
13,1289273,Payday loan,NaN,Can't contact lender,NaN,TX,78205.0,2015-03-18,2015-03-18,ACE Cash Express Inc.,In progress,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28150,1178179,Credit card,NaN,Late fee,NaN,AR,72160.0,2015-01-01,2015-01-02,U.S. Bancorp,Closed with monetary relief,Yes,No
28152,1178183,Consumer loan,Vehicle loan,Taking out the loan or lease,NaN,GA,30043.0,2015-01-01,2015-01-07,DriveTime,Closed with explanation,Yes,NaN
28153,1178182,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,MN,55105.0,2015-01-01,2015-01-02,Regions,Closed with non-monetary relief,Yes,No
28154,1178181,Payday loan,NaN,Can't stop charges to bank account,NaN,CA,92509.0,2015-01-01,2015-01-07,Moneytree Inc,Closed with explanation,Yes,NaN
28155,1178180,Money transfers,Domestic (US) money transfer,Other transaction issues,NaN,OH,45068.0,2015-01-01,2015-01-02,PayPal,Closed with explanation,Yes,Yes

#### State

In [12]:
print (df['State'].sort_values(ascending=True).unique())
print (len(df['State'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['State'].value_counts(ascending=False))
print("-"*40)
print (df['State'].value_counts(normalize=True, ascending=False)*100)
df[df['State'].isna()]

['AE' 'AK' 'AL' 'AP' 'AR' 'AS' 'AZ' 'CA' 'CO' 'CT' 'DC' 'DE' 'FL' 'GA'
 'GU' 'HI' 'IA' 'ID' 'IL' 'IN' 'KS' 'KY' 'LA' 'MA' 'MD' 'ME' 'MH' 'MI'
 'MN' 'MO' 'MS' 'MT' 'NC' 'ND' 'NE' 'NH' 'NJ' 'NM' 'NV' 'NY' 'OH' 'OK'
 'OR' 'PA' 'PR' 'PW' 'RI' 'SC' 'SD' 'TN' 'TX' 'UT' 'VA' 'VI' 'VT' 'WA'
 'WI' 'WV' 'WY' nan]
60
----------------------------------------
State
CA    3859
FL    2592
TX    2380
NY    1846
GA    1146
NJ    1113
PA    1055
IL    1003
OH     939
VA     869
MD     791
NC     764
MI     694
AZ     578
MA     512
WA     509
CO     483
TN     473
SC     441
MO     409
AL     358
NV     351
WI     351
OR     337
MN     311
IN     298
CT     287
LA     277
KY     225
OK     207
UT     176
KS     176
DC     168
MS     159
NM     155
DE     152
IA     141
AR     121
ME     115
ID     115
NH     111
NE     108
RI      89
HI      83
WV      70
PR      65
VT      55
SD      52
MT      41
ND      30
WY      30
AK      25
AP      17
AE       9
VI       7
GU       3
MH       2
PW       1
AS       1
Name: count, dtype: int64
----------------------------------------
State
CA    13.913827
FL     9.345592
TX     8.581215
NY     6.655850
GA     4.131963
NJ     4.012980
PA     3.803858
IL     3.616369
OH     3.385614
VA     3.133225
MD     2.851992
NC     2.754642
MI     2.502253
AZ     2.084009
MA     1.846043
WA     1.835226
CO     1.741482
TN     1.705426
SC     1.590049
MO     1.474671
AL     1.290788
NV     1.265549
WI     1.265549
OR     1.215071
MN     1.121327
IN     1.074455
CT     1.034794
LA     0.998738
KY     0.811249
OK     0.746349
UT     0.634577
KS     0.634577
DC     0.605733
MS     0.573283
NM     0.558861
DE     0.548044
IA     0.508383
AR     0.436272
ME     0.414639
ID     0.414639
NH     0.400216
NE     0.389400
RI     0.320894
HI     0.299261
WV     0.252389
PR     0.234361
VT     0.198305
SD     0.187489
MT     0.147828
ND     0.108167
WY     0.108167
AK     0.090139
AP     0.061294
AE     0.032450
VI     0.025239
GU     0.010817
MH     0.007211
PW     0.003606
AS     0.003606
Name: proportion, dtype: float64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068.0,2015-03-19,2015-03-19,Transworld Systems Inc.,In progress,Yes,NaN
393,1280320,Debt collection,Payday loan,Communication tactics,Threatened to take legal action,NaN,NaN,2015-03-12,2015-03-16,"Enova International, Inc.",Closed with explanation,Yes,NaN
399,1279149,Credit reporting,NaN,Credit reporting company's investigation,No notice of investigation status/result,NaN,33027.0,2015-03-12,2015-03-12,Experian,Closed with explanation,Yes,NaN
410,1279169,Credit reporting,NaN,Unable to get credit report/credit score,Problem getting my free annual report,NaN,32174.0,2015-03-12,2015-03-12,Equifax,Closed with explanation,Yes,NaN
435,1280831,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,95476.0,2015-03-12,2015-03-12,Equifax,In progress,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27782,1178112,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,NaN,85395.0,2015-01-02,2015-01-02,Seterus,Closed with explanation,Yes,Yes
27865,1179252,Money transfers,International money transfer,Fraud or scam,NaN,NaN,NaN,2015-01-02,2015-01-08,Western Union,Closed with explanation,Yes,NaN
27881,1179425,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,37075.0,2015-01-02,2015-01-08,Bank of America,Closed with explanation,Yes,No
27919,1178270,Credit card,NaN,Credit card protection / Debt protection,NaN,NaN,11.0,2015-01-02,2015-01-07,Capital One,Closed with explanation,Yes,NaN
27986,1178370,Bank account or service,Checking account,"Account opening, closing, or management",NaN,NaN,NaN,2015-01-02,2015-01-05,Regions,Closed with explanation,Yes,NaN

#### ZIP code

In [13]:
df['ZIP code'] = df['ZIP code'].astype('Int64')
print (df['ZIP code'].sort_values(ascending=True).unique())
print("-"*40)
print (df['ZIP code'].value_counts(ascending=False))
df[df['ZIP code'].isna()]

<IntegerArray>
[    9,    11,    19,    20,    24,   100,   146,   336,   424,   601,
 ...
 99705, 99708, 99712, 99762, 99821, 99841, 99901, 99926, 99999,  <NA>]
Length: 9869, dtype: Int64
----------------------------------------
ZIP code
76116    58
33173    39
33614    38
85032    37
60445    36
         ..
25003     1
72633     1
35452     1
53183     1
10470     1
Name: count, Length: 9868, dtype: Int64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
393,1280320,Debt collection,Payday loan,Communication tactics,Threatened to take legal action,NaN,<NA>,2015-03-12,2015-03-16,"Enova International, Inc.",Closed with explanation,Yes,NaN
783,1277090,Credit reporting,NaN,Credit reporting company's investigation,Investigation took too long,NV,<NA>,2015-03-10,2015-03-11,Experian,Closed with explanation,Yes,NaN
784,1277088,Credit reporting,NaN,Credit reporting company's investigation,Investigation took too long,NV,<NA>,2015-03-10,2015-03-11,Equifax,Closed with explanation,Yes,NaN
834,1273640,Debt collection,"Other (phone, health club, etc.)",Disclosure verification of debt,Not given enough info to verify debt,NaN,<NA>,2015-03-09,2015-03-13,"Account Control Systems, Inc",Closed with explanation,Yes,NaN
951,1275151,Bank account or service,Other bank product/service,"Account opening, closing, or management",NaN,NaN,<NA>,2015-03-09,2015-03-11,Navy FCU,In progress,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27865,1179252,Money transfers,International money transfer,Fraud or scam,NaN,NaN,<NA>,2015-01-02,2015-01-08,Western Union,Closed with explanation,Yes,NaN
27986,1178370,Bank account or service,Checking account,"Account opening, closing, or management",NaN,NaN,<NA>,2015-01-02,2015-01-05,Regions,Closed with explanation,Yes,NaN
28024,1178472,Debt collection,NaN,Cont'd attempts collect debt not owed,Debt is not mine,NV,<NA>,2015-01-02,2015-01-05,"Medical Data Systems, Inc.",Closed with explanation,Yes,NaN
28070,1177977,Debt collection,Medical,Disclosure verification of debt,Not given enough info to verify debt,NV,<NA>,2015-01-01,2015-01-01,Patient Accounting Service Center,Closed with explanation,Yes,Yes
28085,1178003,Mortgage,Conventional fixed mortgage,Settlement process and costs,NaN,NV,<NA>,2015-01-01,2015-01-01,State Farm Bank,Closed with explanation,Yes,Yes

### Tabla de State y Codigos ZIP de US: "zip_code_database.csv"

El código ZIP (de la sigla en inglés "Zoning Improvement Plan") es un código postal que sirve para identificar áreas geográficas con fines de entrega de correo. Un código FIPS (de la sigla en inglés "Federal Information Processing Standard") es un código numérico utilizado por el gobierno de EE. UU. para identificar de manera única estados, condados y otras subdivisiones geográficas.

In [14]:
df_ZIPcode = pd.read_csv ("zip_code_database.csv", sep=",")
df_ZIPcode.head()

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population
0,501,UNIQUE,0,Holtsville,NaN,Internal Revenue Service,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Internal Revenue Service,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,601,STANDARD,0,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.16,-66.72,0
3,602,STANDARD,0,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,Aguada Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.38,-67.18,0
4,603,STANDARD,0,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.43,-67.15,0

In [15]:
df_zip_code = pd.read_csv ("zip_code_database.csv", sep=",")
df_zip_code = df_zip_code.rename(columns={'state': 'State_ref' ,'primary_city': 'City_ref', 'zip': 'ZIP_ref'})
df_zip = df_zip_code[['ZIP_ref','City_ref' ,'State_ref']]
# print (df_ZIP[df_ZIP['ZIP_ref'] == 43068])

# Guardamos el archivo df_zip.csv
df_zip.to_csv('df_zip.csv', index=False, header=True)
df_zip

       ZIP_ref     City_ref State_ref
0          501   Holtsville        NY
1          544   Holtsville        NY
2          601     Adjuntas        PR
3          602       Aguada        PR
4          603    Aguadilla        PR
...        ...          ...       ...
42730    99926   Metlakatla        AK
42731    99927  Point Baker        AK
42732    99928    Ward Cove        AK
42733    99929     Wrangell        AK
42734    99950    Ketchikan        AK

[42735 rows x 3 columns]

### Date received and Date sent to company = Delivery time

In [16]:
df['Date received'] = pd.to_datetime(df['Date received'])
df['Date sent to company'] = pd.to_datetime(df['Date sent to company'])
df['Delivery Time'] = (df['Date sent to company'] - df['Date received'])
df['Delivery Time'] = df['Delivery Time'].dt.days
print(df.dtypes)
print("-"*40)
print (df['Delivery Time'].sort_values(ascending=True).unique())
print("-"*40)
print (df['Delivery Time'].value_counts(ascending=False))
df = df.drop(columns=['Date received', 'Date sent to company'])
df

Complaint ID                     int64
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
State                           object
ZIP code                         Int64
Date received           datetime64[ns]
Date sent to company    datetime64[ns]
Company                         object
Company response                object
Timely response?                object
Consumer disputed?              object
Delivery Time                    int64
dtype: object
----------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 52 53 55 57 59 60 61 64]
----------------------------------------
Delivery Time
0     12987
1      4352
5      2043
6      1850
3      1684
7      1522
4      1016
2       606
8       373
9       178
10      135
13      116
11      106
19       94
12       81
14       81
15       78
21       76
18       63
20       59
17       58
16       55
22       46
35       38
27       37
26       34
23       31
42       30
24       30
36       28
25       27
30       26
28       24
29       24
31       23
34       20
32       15
39       14
37       13
43       12
33       11
38        9
45        9
41        8
40        7
46        6
44        6
48        4
61        2
47        2
59        1
64        1
57        1
60        1
53        1
52        1
55        1
Name: count, dtype: int64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Company,Company response,Timely response?,Consumer disputed?,Delivery Time
0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119,"Premium Asset Services, LLC",In progress,Yes,NaN,0
1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN,0
2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127,RBS Citizens,Closed with explanation,Yes,Yes,0
3,1291615,Credit card,NaN,Other,NaN,CA,92592,Navy FCU,In progress,Yes,NaN,0
4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068,Transworld Systems Inc.,In progress,Yes,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28151,1178184,Debt collection,NaN,Cont'd attempts collect debt not owed,Debt is not mine,TX,75201,"Enhanced Recovery Company, LLC",Closed with non-monetary relief,Yes,No,1
28152,1178183,Consumer loan,Vehicle loan,Taking out the loan or lease,NaN,GA,30043,DriveTime,Closed with explanation,Yes,NaN,6
28153,1178182,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,MN,55105,Regions,Closed with non-monetary relief,Yes,No,1
28154,1178181,Payday loan,NaN,Can't stop charges to bank account,NaN,CA,92509,Moneytree Inc,Closed with explanation,Yes,NaN,6
28155,1178180,Money transfers,Domestic (US) money transfer,Other transaction issues,NaN,OH,45068,PayPal,Closed with explanation,Yes,Yes,1

### Company

In [17]:
print (df['Company'].sort_values(ascending=True).unique())
print (len(df['Company'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Company'].value_counts(ascending=False))
print("-"*40)
print (df['Company'].value_counts(normalize=True, ascending=False)*100)

['1st Franklin Financial Corporation' '1st Portfolio Holding Corporation'
 '21st Mortgage Corporation' ... 'Zions Bancorporation'
 'Zwicker & Associates' 'iQuantified Management Services, LLC']
1534
----------------------------------------
Company
Equifax                             2049
Experian                            1940
TransUnion                          1525
Bank of America                     1518
Wells Fargo                         1430
                                    ...
Collection Bureau Services, Inc.       1
Town Financial Corporation             1
Credit Services of Oregon, Inc.        1
Presto Auto Loans, Inc.                1
IMMEDIATE RECOVERY GROUP, INC          1
Name: count, Length: 1534, dtype: int64
----------------------------------------
Company
Equifax                             7.277312
Experian                            6.890183
TransUnion                          5.416252
Bank of America                     5.391391
Wells Fargo                         5.078846
                                      ...
Collection Bureau Services, Inc.    0.003552
Town Financial Corporation          0.003552
Credit Services of Oregon, Inc.     0.003552
Presto Auto Loans, Inc.             0.003552
IMMEDIATE RECOVERY GROUP, INC       0.003552
Name: proportion, Length: 1534, dtype: float64

### Company response

In [18]:
print (df['Company response'].sort_values(ascending=True).unique())
print (len(df['Company response'].sort_values(ascending=True).unique()))
print("-"*40)
print (df['Company response'].value_counts(ascending=False))
print("-"*40)
print (df['Company response'].value_counts(normalize=True, ascending=False)*100)

['Closed' 'Closed with explanation' 'Closed with monetary relief'
 'Closed with non-monetary relief' 'In progress' 'Untimely response']
6
----------------------------------------
Company response
Closed with explanation            19381
Closed with non-monetary relief     3593
In progress                         2690
Closed with monetary relief         1534
Closed                               606
Untimely response                    352
Name: count, dtype: int64
----------------------------------------
Company response
Closed with explanation            68.834351
Closed with non-monetary relief    12.761046
In progress                         9.553914
Closed with monetary relief         5.448217
Closed                              2.152294
Untimely response                   1.250178
Name: proportion, dtype: float64

### Timely response

In [19]:
print (df['Timely response?'].sort_values(ascending=True).unique())
print("-"*40)
print (df['Timely response?'].value_counts(ascending=False))
print("-"*40)
print (df['Timely response?'].value_counts(normalize=True, ascending=False)*100)

['No' 'Yes']
----------------------------------------
Timely response?
Yes    27444
No       712
Name: count, dtype: int64
----------------------------------------
Timely response?
Yes    97.471232
No      2.528768
Name: proportion, dtype: float64

### Consumer disputed?

In [20]:
print (df['Consumer disputed?'].sort_values(ascending=True).unique())
print("-"*40)
print (df['Consumer disputed?'].value_counts(ascending=False))
print("-"*40)
print (df['Consumer disputed?'].value_counts(normalize=True, ascending=False)*100)
df[df['Consumer disputed?'].isna()]

['No' 'Yes' nan]
----------------------------------------
Consumer disputed?
Yes    4708
No     1298
Name: count, dtype: int64
----------------------------------------
Consumer disputed?
Yes    78.388278
No     21.611722
Name: proportion, dtype: float64

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Company,Company response,Timely response?,Consumer disputed?,Delivery Time
0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119,"Premium Asset Services, LLC",In progress,Yes,NaN,0
1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN,0
3,1291615,Credit card,NaN,Other,NaN,CA,92592,Navy FCU,In progress,Yes,NaN,0
4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068,Transworld Systems Inc.,In progress,Yes,NaN,0
5,1291176,Debt collection,Payday loan,Communication tactics,Called after sent written cease of comm,OH,43068,ACE Cash Express Inc.,In progress,Yes,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28146,1178169,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,WA,98908,Experian,Closed with explanation,Yes,NaN,6
28147,1178178,Consumer loan,Installment loan,Problems when you are unable to pay,NaN,CA,94583,"CashCall, Inc.",Closed with explanation,Yes,NaN,6
28148,1178176,Debt collection,Non-federal student loan,Disclosure verification of debt,Right to dispute notice not received,MI,48622,Transworld Systems Inc.,Closed with explanation,Yes,NaN,5
28152,1178183,Consumer loan,Vehicle loan,Taking out the loan or lease,NaN,GA,30043,DriveTime,Closed with explanation,Yes,NaN,6
28154,1178181,Payday loan,NaN,Can't stop charges to bank account,NaN,CA,92509,Moneytree Inc,Closed with explanation,Yes,NaN,6

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28156 entries, 0 to 28155
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Complaint ID        28156 non-null  int64
 1   Product             28156 non-null  object
 2   Sub-product         17582 non-null  object
 3   Issue               28154 non-null  object
 4   Sub-issue           13211 non-null  object
 5   State               27735 non-null  object
 6   ZIP code            27876 non-null  Int64
 7   Company             28156 non-null  object
 8   Company response    28156 non-null  object
 9   Timely response?    28156 non-null  object
 10  Consumer disputed?  6006 non-null   object
 11  Delivery Time       28156 non-null  int64
dtypes: Int64(1), int64(2), object(9)
memory usage: 2.6+ MB

In [22]:
# Guardamos el archivo df_main.csv
df.to_csv('df_main.csv', index=False, header=True)

### Archivos para limpieza y referencia.

In [23]:
df_main = pd.read_csv ("df_main.csv", sep=",")
df_main["ZIP code"] = df_main["ZIP code"].astype("Int64")
df_main.info()
df_main

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28156 entries, 0 to 28155
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Complaint ID        28156 non-null  int64
 1   Product             28156 non-null  object
 2   Sub-product         17582 non-null  object
 3   Issue               28154 non-null  object
 4   Sub-issue           13211 non-null  object
 5   State               27735 non-null  object
 6   ZIP code            27876 non-null  Int64
 7   Company             28156 non-null  object
 8   Company response    28156 non-null  object
 9   Timely response?    28156 non-null  object
 10  Consumer disputed?  6006 non-null   object
 11  Delivery Time       28156 non-null  int64
dtypes: Int64(1), int64(2), object(9)
memory usage: 2.6+ MB

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Company,Company response,Timely response?,Consumer disputed?,Delivery Time
0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119,"Premium Asset Services, LLC",In progress,Yes,NaN,0
1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN,0
2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127,RBS Citizens,Closed with explanation,Yes,Yes,0
3,1291615,Credit card,NaN,Other,NaN,CA,92592,Navy FCU,In progress,Yes,NaN,0
4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068,Transworld Systems Inc.,In progress,Yes,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28151,1178184,Debt collection,NaN,Cont'd attempts collect debt not owed,Debt is not mine,TX,75201,"Enhanced Recovery Company, LLC",Closed with non-monetary relief,Yes,No,1
28152,1178183,Consumer loan,Vehicle loan,Taking out the loan or lease,NaN,GA,30043,DriveTime,Closed with explanation,Yes,NaN,6
28153,1178182,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,MN,55105,Regions,Closed with non-monetary relief,Yes,No,1
28154,1178181,Payday loan,NaN,Can't stop charges to bank account,NaN,CA,92509,Moneytree Inc,Closed with explanation,Yes,NaN,6
28155,1178180,Money transfers,Domestic (US) money transfer,Other transaction issues,NaN,OH,45068,PayPal,Closed with explanation,Yes,Yes,1

### Archivo de referencia y API de verificación US_ZIP_code. 

(WEB): https://www.zip-codes.com

(API): https://api.zip-codes.com/ZipCodesAPI.svc/1.0/<endpoint>?key=<APIKEY>

In [24]:
df_zip = pd.read_csv ("df_zip.csv", sep=",")
df_zip.info()
df_zip

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42735 entries, 0 to 42734
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ZIP_ref    42735 non-null  int64
 1   City_ref   42735 non-null  object
 2   State_ref  42735 non-null  object
dtypes: int64(1), object(2)
memory usage: 1001.7+ KB

       ZIP_ref     City_ref State_ref
0          501   Holtsville        NY
1          544   Holtsville        NY
2          601     Adjuntas        PR
3          602       Aguada        PR
4          603    Aguadilla        PR
...        ...          ...       ...
42730    99926   Metlakatla        AK
42731    99927  Point Baker        AK
42732    99928    Ward Cove        AK
42733    99929     Wrangell        AK
42734    99950    Ketchikan        AK

[42735 rows x 3 columns]